language: node_js
node_js:
  - '8.11.4'
cache:
  directories:
    - node_modules
stages:
  - name: deploy-prod
    if: branch = production
  - name: deploy-dev
    if: branch = master
jobs:
  include:
    - stage: deploy-prod
      script: ./deploy/deploy-prod.sh
    - stage: deploy-dev
      script: ./deploy/deploy-dev.sh
